const list = [
  ["das Lebensmittel", "продукт питания"],
  ["der Apfel", "яблоко"],
  ["die Banane", "банан"],
  ["die Birne", "груша"],
  ["das Brot", "хлеб"],
  ["das Brötchen", "булочка"],
  ["das Ei", "яйцо"],
  ["der Fisch", "рыба"],
  ["das Getränk", "напиток"],
  ["die Kartoffel", "картофель; картошка"],
  ["der Kuchen", "пирог"],
  ["die Orange", "апельсин"],
  ["der Saft", "сок"],
  ["der Salat", "салат"],
  ["die Tomate", "помидор"],
  ["die Traube", "гроздь винограда; кисть винограда"],
  ["die Wurst", "колбаса"],
  ["das Bier", "пиво"],
  ["die Butter", "масло; сливочное масло"],
  ["die Cola", "кола"],
  ["das Fleisch", "мясо; мякоть; плоть"],
  ["das Gemüse", "овощи"],
  ["der Kaffee", "кофе"],
  ["der Käse", "сыр"],
  ["die Milch", "молоко"],
  ["das Mineralwasser", "минеральная вода"],
  ["das Obst", "фрукты"],
  ["das Öl", "масло; растительное масло"],
  ["der Reis", "рис"],
  ["die Sahne", "сливки"],
  ["das Salz", "соль"],
  ["der Schinken", "ветчина"],
  ["der Tee", "чай"],
  ["der Wein", "вино"],
  ["das Lieblingsessen", "любимая еда"],
  ["das Lieblingsgetränk", "любимый напиток"],
  ["das Essen", "пища; еда"],
  ["das Hähnchen", "курица"],
  ["Pommes", "картофель фри; картошка фри"],
  ["die Suppe", "суп"],
  ["die Soße", "соус; подливка"],
  ["durst haben", "хотеть пить; испытывать жажду"],
  ["hunger haben", "хотеть есть; испытывать голод; быть голодным"],
  ["essen", "есть; кушать"],
  ["du isst", "ты ешь; ты кушаешь"],
  ["er isst", "он ест; он кушает"],
  ["schmecken", "пробовать на вкус; пробовать"],
  ["trinken", "пить"],
  ["lecker", "вкусный; вкусно"],
  ["der Preis", "цена"],
  ["der Euro", "евро"],
  ["der Cent", "цент"],
  ["kosten", "стоить"],
  ["wie viel", "сколько; как много"],
  ["das Gewicht", "вес; тяжесть"],
  ["das Gramm", "грамм"],
  ["das Pfund", "фунт; полкилограмма"],
  ["das Kilo", "килограмм"],
  ["der Liter", "литр"],
  ["der Becher", "стакан; стаканчик"],
  ["die Dose", "консервная банка; банка"],
  ["die Flasche", "бутылка"],
  ["die Packung", "упаковка; пачка"],
  ["der Einkauf", "покупка"],
  ["der Markt", "рынок; базар"],
  ["die Person", "лицо; персона; человек"],
  ["der Prospekt", "проспект"],
  ["das Restaurant", "ресторан"],
  ["das Sonderangebot", "распродажа"],
  ["der Supermarkt", "супермаркет"],
  ["das Wörterbuch", "словарь"],
  ["antworten", "отвечать; давать ответ; ответить"],
  ["brauchen", "нуждаться; иметь потребность"],
  ["glauben", "полагать; верить"],
  ["helfen", "помогать; помочь"],
  ["du hilfst", "ты помогаешь"],
  ["er hilft", "он помогает"],
  ["kaufen", "купить; покупать"],
  ["möchten", "хотеть"],
  ["nennen", "называть; давать имя"],
  ["notieren", "отмечать; замечать; записывать"],
  ["zeichnen", "рисовать; чертить"],
  ["etwas", "что-то; что-нибудь"],
  ["gern", "охотно; с удовольствием"],
  ["kein", "не; отрицание"],
  ["natürlich", "конечно; естественно"],
  ["sonst", "иначе; а то; не то; в противном случае"],
  ["vielleicht", "может быть; возможно; пожалуй"],
  ["weiter", "дальше; далее"],
  ["auf Deutsch", "по немецки; на немецком"],
  ["zum Beispiel", "например; к примеру"],
  ["Wie bitte?", "Что, простите?"],
  ["zu Hause", "дома"],
];

export { list };
